-- CreateTable
CREATE TABLE "Door" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "isClosed" BOOLEAN NOT NULL
);

-- CreateTable
CREATE TABLE "DoorLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "doorId" INTEGER NOT NULL,
    "isClosed" BOOLEAN NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DoorLog_doorId_fkey" FOREIGN KEY ("doorId") REFERENCES "Door" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
